#!/bin/bash

curl -X POST "https://gitlab.com/api/v4/projects/MissRea09%2Fknitwebsite/merge_requests" \
  -H "PRIVATE-TOKEN: glpat-GM83G7golFj936sQYiXlIWM6MQpvOjEKdTprenl4NA8.01.170bmduvq" \
  -H "Content-Type: application/json" \
  -d '{
    "source_branch": "Knit_websiteV2",
    "target_branch": "main",
    "title": "🚀 Knit Website V2 - Enhanced User Experience & Performance",
    "description": "# 🚀 Knit Website V2 - Enhanced User Experience & Performance\n\n## 📋 Overview\nThis merge request introduces significant improvements to the Knit website, focusing on enhanced user experience, modern UI components, and streamlined legal content presentation. The changes maintain brand consistency while improving accessibility and engagement.\n\n## ✨ Key Features & Improvements\n\n### 🎨 User Experience Enhancements\n- **Modernized Terms of Service page** with improved visual hierarchy\n- **Streamlined legal content structure** for better readability\n- **Enhanced responsive design** across all device sizes\n- **Improved accessibility** with semantic HTML and ARIA compliance\n\n### 🛠 Technical Improvements\n- **Performance optimizations** with memoized React components\n- **Code organization improvements** with reusable UI patterns\n- **Enhanced maintainability** through component-based architecture\n- **Better error handling** and user feedback mechanisms\n\n## 🔍 Changes Summary\n\n### Core Components Modified\n- `components/TermsOfServicePage.tsx` - Complete redesign with modern UI patterns\n- Enhanced contact section with dynamic navigation\n- Improved legal content presentation and structure\n\n## 🧪 Testing & Quality Assurance\n\n### ✅ Verified Functionality\n- [x] All navigation links work correctly\n- [x] Responsive design tested on mobile, tablet, and desktop\n- [x] Accessibility compliance with WCAG guidelines\n- [x] Cross-browser compatibility (Chrome, Firefox, Safari)\n\n## 🚦 Deployment Considerations\n\n### Breaking Changes\n- None - All changes are backward compatible\n- Existing APIs and routes remain unchanged\n- No database migrations required\n\n## 🤝 Review Checklist\n\n### For Reviewers\n- [ ] Verify all legal content is accurate and up-to-date\n- [ ] Test responsive design on various screen sizes\n- [ ] Confirm accessibility compliance\n- [ ] Validate performance improvements\n\n---\n\n*This MR represents a significant step forward in our website'\''s evolution, balancing modern design principles with legal compliance and performance optimization.*",
    "labels": ["enhancement", "ui/ux", "performance", "accessibility"]
  }'
